# Chunk rejection reason codes
INVALID_STRUCTURE = "INVALID_STRUCTURE"
INVALID_CONTENT = "INVALID_CONTENT"
JUNK_CHUNK = "JUNK_CHUNK"
EMPTY_AFTER_CLEANING = "EMPTY_AFTER_CLEANING"
GIBBERISH_LINES = "GIBBERISH_LINES"
HARD_LOWER_THRESHOLD = "HARD_LOWER_THRESHOLD"
SOFT_THRESHOLD_FAIL = "SOFT_THRESHOLD_FAIL"
SHORT_SENTENCE_LENGTH = "SHORT_SENTENCE_LENGTH"
